language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L https://raw.githubusercontent.com/jdlnolen/zombie/master/configure.sh | /bin/sh"
services:
  - mongodb
before_script:
  - mrt
  - sleep 3
script: ./run.sh
